### ISSUE TITLE
Is this plugin supported.

### ISSUE THREAD

**Issue by SBPrime** [blha303/HGMGS#1]
Hi
I would like to know if this plugin is still supported? If so I would like to report a problem on spigot 1.8. I managed to configura a default arena but after i typed /hg join (2 players, minimum was also set to 2 players) then /hg start nothing happened. When I tp'ed to the arena world it was all flat.

**Comment by blha303** [comment]
Hey, this was never my plugin, I just put the source on github for reference. It won't work on any version after 1.6.2 anyway. Sorry.
